# the name of your event
name = ""Sunset" Dinner and Social"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@yunigraham"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
# website = "https://lu.ma/ipfsthing-sunsetdinner-14"

# the start date of the event
date = "2022-07-14"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "19:00 - 24:00"

# the event venue name (will show up on the event card - TODO)
venueName = "Ballroom B & Sunset"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Reykjavik Edition Hotel"

# the max number of attendees of the event
attendees = "100"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Dinner"]

# a color, to group key events visually. use sparingly
color="indigo"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Join us for dinner in Ballroom B of the Reykjavik Edition followed by music and drinks in Sunset. 
"""
